name: Change shell        # ワークフロー名
on:
  push:
jobs:
  print:
    runs-on: ubuntu-latest
    timeout-minutes: 1      # タイムアウトする時間を1分に設定
    steps:
      - shell: bash
        run: echo "${SHELL}"
      - shell: python
        run: |
          import os
          print(os.environ['PATH'])

# 起動シェルをステップごとに変更できる
## > 一つのワークフローの中で複数のシェルを切り替えて実行することできる

## シェルがパイソンって不思議な感じ
### bashの代わりにpythonで実行している　ランナー（Ubuntu・windows・macos）すべてこれで実行している

# shellを指定しなくても実行することはできるが実行されるときのオプションが異なる
# 省略時 bash -e {0}
# 記載時 bash --noprofile --norc -eo pipefail {0}
# 特に重要なのがpipefailのオプション
## この指定がないとパイプでエラーになってしまっているのに気づけない

#  bash
#  ├─ 個人設定を読まない　--noprofile
#  ├─ aliasを無効化
#  ├─ エラー即停止
#  ├─ パイプも厳密判定
#  └─ run内容を実行
## CIで実行
